#公共配置
server:
    port: 8088
    tomcat:
      uri-encoding: UTF-8
    servlet:
      context-path: /wb/


spring:
    #激活哪一个环境的配置文件
    profiles:
      active: dev
#    http:
#      multipart:
#        max-file-size: 100MB
#        max-request-size: 100MB
#        maxFileSize: 100MB
#        maxRequestSize: 100MB

work_base:
  show_system_name: 微博辅助系统

#mybatisPlu
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.jackssy.admin.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
       #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    #刷新mapper
    refresh-mapper: true
  #原生配置
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志
logging:
  config: classpath:logback.xml
  path: D:\logs\comadmin
uvstatics:
          url:
            prefix: http://localhost:8088/uv/{phoneNum}/{productId}
            default : http://www.baidu.com

---
#开发环境配置
spring:
  profiles: dev
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://59.110.240.154:3306/weibo_info?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root1234
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 30
jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    password:
    timeout: 2000
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000
server:
  #端口
  port: 8088

---
#开发环境配置
spring:
  profiles: prd
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/comadmin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 30
  thymeleaf:
    cache: false
jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    password:
    timeout: 2000
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000
server:
  #端口
  port: 8090


