#公共配置
server:
    port: 8088
    tomcat:
      uri-encoding: UTF-8

spring:
    #激活哪一个环境的配置文件
    profiles:
      active: prd
    servlet:
      multipart:
        maxFileSize: 100Mb
        maxRequestSize: 100Mb
#mybatisPlu
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.jackssy.admin.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
       #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    #刷新mapper
    refresh-mapper: true
  #原生配置
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
#开发环境配置
spring:
  profiles: dev
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/uvstatics_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root1234
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 50
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
server:
  #端口
  port: 8088
#日志
logging:
  config: classpath:logback.xml
  path: D:\logs\uvstatics_base
uvstatics:
  url:
    prefix: http://localhost:8088/uv/{phoneNumber}/{productId}
    default : http://www.baidu.com
    exportSmsName: 导出手机短信模板
    savePhoneFilePath: d://data//product//

---
#开发环境配置
spring:
  profiles: prd
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/uvstatics_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 50
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
server:
  #端口
  port: 8090
#日志
logging:
  config: classpath:logback.xml
  path: /root/data/uvstatics_base/logs
uvstatics:
  url:
    prefix: http://59.110.240.154:8090/uv/{phoneNumber}/{productId}
    default : http://www.baidu.com
    exportSmsName: 导出手机短信模板
    savePhoneFilePath: /root/data/uvstatics_base/data/product/



